### ISSUE TITLE
Counting subslides

### ISSUE THREAD

**Issue by palainp** [andreasKroepelin/typst-slides#19]
Hi, I'm trying to write a template and I want to add a "count bullet points" while the sub slides are rolling out. I have something like:
```
  let displayed-header(slide-info) = {
    let filledcircle(..nums) = {
      range(0, nums.pos().first()).map(_ => sym.circle.filled).join()
    }
    if "title" in slide-info {
      text(size: 1.2em, fill: clear, slide-info.title ) + h(1fr) + text(size: .5em, fill: clear,  subslide.display(filledcircle) )
    } else {
      text(size: 1.2em, fill: clear, section.display() ) + h(1fr) + text(size: .5em, fill: clear,  subslide.display(filledcircle) )
    }
  }
```
It works fine, but I haven't figured out how to add the remaining `sym.circle.stroked` (from the current subslide value+1 to the maximum subslide value). Is there a way to do this?

**Comment by andreasKroepelin** [comment]
I don't think there currently is a reliable way to do that, I'm sorry. Read https://andreaskroepelin.github.io/typst-slides/book/dynamic.html#internal-number-of-repetitions for some background details.
