### ISSUE TITLE
Support for pdfpc overlays (override page numbers)

### ISSUE THREAD

**Issue by naps62** [andreasKroepelin/typst-slides#38]
I use both this template, and since more recently, https://pdfpc.github.io/ for a keynote-style app with speaker notes support

One feature of pdfpc that I haven't used yet are Overlays: pdfpc tries to identify slides that are transitions between themselves (e.g.: a typical bullet list where every new slide reveals a new item). It tries to infer this by looking at the page number, and then the speaker view handles this accordingly (e.g.: showing the speaker notes for that bullet list on all those slides)

Would it be possible to somehow override the current page number counter in a way that plays nicely with this? e.g.: tell a given slide that it should not increment the number

**Comment by naps62** [comment]
oh silly me. I just dove into the latest version. it seems `#uncover` already handles exactly what I want?

**Comment by andreasKroepelin** [comment]
I invite you to read this page in the book:
https://andreaskroepelin.github.io/typst-slides/book/dynamic.html

For a bullet list, this would be a convenient option:
```typ
#line-by-line[
  - abc
  - def
  - ghi
]
```
