### ISSUE TITLE
Have themes

### ISSUE THREAD

**Issue by andreasKroepelin** [andreasKroepelin/typst-slides#5]
It would be nice if user could choose from different themes that change colors and decoration etc.

**Comment by astrale-sharp** [comment]
I'll start working on that id that's okay :)

**Comment by andreasKroepelin** [comment]
> I get `` thread 'main' panicked at 'assertion failed: min <= max', /rustc/8460ca823e8367a30dda430efda790588b8c84d3/library/core/src/cmp.rs:867:9 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace [Info - 20:20:47] Connection to server got closed. Server will restart. `` when changing the `footer-descent`

That's definitly a bug in Typst, you could open an issue at their repository.

**Comment by andreasKroepelin** [comment]
I'm not so sure how you plan to then use a theme that was created by such a function. Could you elaborate on that, please?
Also I think `max-repetitions` should remain a slide-wise parameter. I will document that more properly soon.

**Comment by andreasKroepelin** [comment]
+1 for as much customisation as possible, but I also want to have good defaults so you don't have do bother if you don't care. Having like a giant config dict probably goes in the right direction. I will think some more about this.

**Comment by PgBiel** [comment]
> +1 for as much customisation as possible, but I also want to have good defaults so you don't have do bother if you don't care.

Of course. I also believe we should accept parameters that can _optionally_ be functions when possible. And, when omitted, just use the default that we define in the base theme.

> Having like a giant config dict probably goes in the right direction. 

It's surely a way around having to pass tons of parameters to the lambdas. Though, we must be careful in case we need to change this API in the future. Maybe we should add some sort of versioning to the dict (e.g. a "version: 1" attribute).

**Comment by astrale-sharp** [comment]
As you can see in the resulting pdf of this file in  #9 
https://github.com/andreasKroepelin/typst-slides/pull/9/files#diff-9dd1de82bc484dee7d772cfae39f50037ed841d2feb75afdea1d674d0e8dc32d

![image](https://user-images.githubusercontent.com/53686698/228826355-1cca399e-2a2d-4722-9196-ddbdd2a38237.png)
![image](https://user-images.githubusercontent.com/53686698/228826397-9bd11aff-349e-40b5-b3c6-476785704803.png)

susbslides takes a weird value of 11 for the last slide.

**Comment by andreasKroepelin** [comment]
Resolved by #11
