### ISSUE TITLE
Document boxing of hiddden content

### ISSUE THREAD

**Issue by andreasKroepelin** [andreasKroepelin/typst-slides#7]
The book should contain some description of why and how we `#box` the content that is about to be hidden. Maybe in a "Development" section? Depends on how important that is to users of the template.

@PgBiel would you like to have a go at this?

**Comment by andreasKroepelin** [comment]
> What do you think about also adding a parameter to `one-by-one` (and other such functions) that lets the user customize the box with a function (that takes the hidden content and returns the modified content)?

We should probably do something like that, yes. Also to allow inline content.

> Maybe we could even pass, as parameters, the slide number and whether or not it should currently be hidden, to allow for more complete customization.

I don't really understand, can you elaborate?

**Comment by PgBiel** [comment]
> We should probably do something like that, yes. Also to allow inline content.

Perfect.

> I don't really understand, can you elaborate?

Oh, I meant, maybe this callback that customizes the `box` could also receive, as parameters, the current slide number and maybe a boolean indicating whether or not the element it is being applied to is currently supposed to be hidden. This way, a user can determine different behavior for a shown and for a hidden object.  (I concede that this might be excessive, though.)

**Comment by PgBiel** [comment]
By the way @andreasKroepelin, an interesting PR was merged in typst: https://github.com/typst/typst/pull/587

Seems like math should be properly hidden now, yay! Though I guess lists are still broken. So yeah lol

**Comment by andreasKroepelin** [comment]
Oh that's nice! I will look into having different modes of hiding stuff soon (in a block (the current behaviour), inline (what we had before your fix), not occupying space when hidden). Currently, I'm overhauling the display system, also making themes simpler by that.

**Comment by PgBiel** [comment]
For reference, another relevant PR (by me :D): https://github.com/typst/typst/pull/644

**Comment by andreasKroepelin** [comment]
Oh that's great! So if that gets merged, we don't need the boxing at all anymore, right?

**Comment by PgBiel** [comment]
> Oh that's great! So if that gets merged, we don't need the boxing at all anymore, right?

It might still be needed for some possible layout quirks, but we might be able to make it optional instead of the default, which is great

**Comment by PgBiel** [comment]
> @PgBiel I played around with the new Typst release from today and everything works nicely without any blocks or boxes sunglasses I have plans for a further simplification of the cover/uncover API, expect a PR soon :D

@andreasKroepelin even lists? My PR wasn't merged yet, because it has blockers due to how internals work
It might only be merged when the style system is reworked; until then, hiding lists will be broken

**Comment by andreasKroepelin** [comment]
Yep, even lists! Bullet points, enumerations, term lists -- everything looks as it should!

**Comment by PgBiel** [comment]
> Yep, even lists! Bullet points, enumerations, term lists -- everything looks as it should!

How is this being done? I can't reproduce this in isolation
![image](https://user-images.githubusercontent.com/9021226/231321972-e8880213-5fbe-4c2a-837a-50d7af703970.png)

**Comment by andreasKroepelin** [comment]
Huh, interesting... Are you using the most recent release? I will have to investigate that in the next days.

**Comment by andreasKroepelin** [comment]
> Yeah; this is on typst's website (which is using v0.2.0).
> 
> (unless you're hiding entire lists; this bug is on individual list items)

Alright, I think I solved it. Due to some state updating stuff, I guess the list items are put into their own lists. So I guess it actually does hide entire list. Nevertheless, it works :D

**Comment by PgBiel** [comment]
> I guess the list items are put into their own lists.

This should probably be fixed then, as it would break continuity between markers (assuming this happens all the time)

Unless you wish to mimic this behavior for boxes - only box list items
That could also work (even though it would also break marker continuity)

**Comment by andreasKroepelin** [comment]
As far as I understand, every working solution would break this continuity currently, right? Only when your PR gets merged this will _really_ work.

**Comment by PgBiel** [comment]
> As far as I understand, every working solution would break this continuity currently, right? Only when your PR gets merged this will _really_ work.

Yep.
The problem with my PR is that the fix I propose would break existing code that uses `show` with lists, as list children wouldn't have to be `listitem` anymore (but rather any `content` - the item's body, directly)

This is why we are currently waiting on a styling rework, to make my fix possible while keeping `listitem` as the only possible children for lists.  (And similar for `enum`/`enumitem`)
(Note that `#hide[]` is implemented using styles, just like colors and stuff)

Another possible fix would be to allow for custom markers in listitems, and those markers could hold the local styles as well, but that would take more discussion (which hasn't started so far)

So yeah... here we are lol

**Comment by andreasKroepelin** [comment]
This has become obsolete by #16
